package com.ericandpau.pokeshopk

class PokemonProvider {
    companion object {
        val pokemons = listOf<Pokemon>(
            Pokemon("Bulbasaur", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"),
            Pokemon("Ivysaur", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png"),
            Pokemon("Venusaur", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png"),
            Pokemon("Charmander", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png"),
            Pokemon("Charmeleon", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png"),
            Pokemon("Charizard", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png"),
            Pokemon("Squirtle", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png"),
            Pokemon("Wartortle", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png"),
            Pokemon("Blastoise", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png"),
            Pokemon("Caterpie", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png"),
            Pokemon("Metapod", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png"),
            Pokemon("Butterfree", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png"),
            Pokemon("Weedle", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png"),
            Pokemon("Kakuna", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png"),
            Pokemon("Beedrill", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png"),
            Pokemon("Pidgey", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png"),
            Pokemon("Pidgeotto", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png"),
            Pokemon("Pidgeot", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png"),
            Pokemon("Rattata", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png"),
            Pokemon("Raticate", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png"),
            Pokemon("Spearow", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png"),
            Pokemon("Fearow", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png"),
            Pokemon("Ekans", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png"),
            Pokemon("Arbok", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png"),
            Pokemon("Pikachu", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png"),
            Pokemon("Raichu", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png"),
            Pokemon("Sandshrew", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png"),
            Pokemon("Sandslash", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png"),
            Pokemon("Nidoran♀", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png"),
            Pokemon("Nidorina", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png"),
            Pokemon("Nidoqueen", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png"),
            Pokemon("Nidoran♂", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png"),
            Pokemon("Nidorino", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png"),
            Pokemon("Nidoking", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png"),
            Pokemon("Clefairy", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png"),
            Pokemon("Clefable", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png"),
            Pokemon("Vulpix", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png"),
            Pokemon("Ninetales", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png"),
            Pokemon("Jigglypuff", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png"),
            Pokemon("Wigglytuff", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png"),
            Pokemon("Zubat", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png"),
            Pokemon("Golbat", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png"),
            Pokemon("Oddish", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png"),
            Pokemon("Gloom", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png"),
            Pokemon("Vileplume", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png"),
            Pokemon("Paras", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png"),
            Pokemon("Parasect", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png"),
            Pokemon("Venonat", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png"),
            Pokemon("Venomoth", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png"),
            Pokemon("Diglett", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png"),
            Pokemon("Dugtrio", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png"),
            Pokemon("Meowth", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png"),
            Pokemon("Persian", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png"),
            Pokemon("Psyduck", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png"),
            Pokemon("Golduck", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png"),
            Pokemon("Mankey", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png"),
            Pokemon("Primeape", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png"),
            Pokemon("Growlithe", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png"),
            Pokemon("Arcanine", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png"),
            Pokemon("Poliwag", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png"),
            Pokemon("Poliwhirl", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png"),
            Pokemon("Poliwrath", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png"),
            Pokemon("Abra", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png"),
            Pokemon("Kadabra", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png"),
            Pokemon("Alakazam", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png"),
            Pokemon("Machop", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png"),
            Pokemon("Machoke", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png"),
            Pokemon("Machamp", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png"),
            Pokemon("Bellsprout", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png"),
            Pokemon("Weepinbell", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png"),
            Pokemon("Victreebel", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png"),
            Pokemon("Tentacool", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png"),
            Pokemon("Tentacruel", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png"),
            Pokemon("Geodude", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png"),
            Pokemon("Graveler", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png"),
            Pokemon("Golem", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png"),
            Pokemon("Ponyta", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png"),
            Pokemon("Rapidash", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png"),
            Pokemon("Slowpoke", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png"),
            Pokemon("Slowbro", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png"),
            Pokemon("Magnemite", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png"),
            Pokemon("Magneton", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png")

        )
    }

}